// import image1 from '../../../public/assets/Icons/JJ.jpg';
import ImagePath from "./index";
const data = [
  {
    src: ImagePath.Naruto,
    data1: "Naruto",
    data2: "Masashi Kishimoto",
    readtime: "13mins",
    totalreadings: "45.5k",
    reading: true,
    id: 1,
  },
  {
    src: ImagePath.OnePiece,
    data1: "Onepiece",
    data2: "Eiichiro Oda",
    readtime: "15mins",
    totalreadings: "60.2k",
    reading: true,
    id: 2,
  },
  {
    src: ImagePath.JJ,
    data1: "Jujutsu Kaisen",
    data2: "Gege Akutami",
    readtime: "12mins",
    totalreadings: "55.8k",
    reading: true,
    id: 3,
  },
  {
    src: ImagePath.Baki,
    data1: "Baki",
    data2: "Keisuke Itagaki",
    readtime: "10mins",
    totalreadings: "40.1k",
    reading: false,
    id: 4,
  },
  {
    src: ImagePath.AOT,
    data1: "Attack on Titan",
    data2: "Hajime Isayama",
    readtime: "18mins",
    totalreadings: "70.3k",
    reading: false,
    id: 5,
  },
  {
    src: ImagePath.DemonSlayer,
    data1: "Demon Slayer",
    data2: "Koyoharu Gotouge",
    readtime: "14mins",
    totalreadings: "48.7k",
    reading: false,
    id: 6,
  },
  {
    src: ImagePath.DeathNote,
    data1: "Death Note",
    data2: "Tsugumi Ohba",
    readtime: "22mins",
    totalreadings: "65.9k",
    reading: true,
    id: 7,
  },
  {
    src: ImagePath.Dragonball,
    data1: "Dragon Ball",
    data2: "Akira Toriyama",
    readtime: "20mins",
    totalreadings: "75.6k",
    reading: false,
    id: 8,
  },
  {
    src: ImagePath.TokyoRevengers,
    data1: "Tokyo Revengers",
    data2: "Ken Wakui",
    readtime: "16mins",
    totalreadings: "52.4k",
    reading: true,
    id: 9,
  },
  {
    src: ImagePath.Boruto,
    data1: "Boruto",
    data2: "Masashi Kishimoto",
    readtime: "17mins",
    totalreadings: "50.9k",
    reading: true,
    id: 10,
  },
];
export default data;
